# Generated by Django 4.2.9 on 2024-02-02 08:10

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0008_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="breads.region",
            ),
        ),
    ]
