# Generated by Django 4.2.9 on 2024-02-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0009_alter_city_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="country",
            new_name="region",
        ),
    ]
