# Generated by Django 4.2.9 on 2024-02-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0010_rename_country_city_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AddField(
            model_name="region",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
        ),
    ]
